import { Assistant, } from 'next/font/google';

import type { Metadata, } from 'next';
import './globals.css';

const assistant = Assistant( {
  variable: '--font-assistant',
  subsets: [ 'latin', ],
}, );

export const metadata : Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout( {
  children,
} : Readonly<{
  children : React.ReactNode;
}>, ) {
  return (
    <html lang="en">
      <body
        className={ `${ assistant.variable } antialiased` }
      >
        { children }
      </body>
    </html>
  );
}
